export WORKSPACE="~/Documents/spring-workspace"
export STORE_PROJECT_HOME="$WORKSPACE/SpringBootOnlineStore"
alias prod="cd $STORE_PROJECT_HOME"
alias startmongo="stopmongo;sh $STORE_PROJECT_HOME/test-mongo/start_mongodb.sh"
alias stopmongo="sh $STORE_PROJECT_HOME/test-mongo/stop_mongodb.sh"
